2021-12-11 21:56:27,332 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alex/Developer/timetableSystem/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block 'html'
    {%- block head %}
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block 'head'
    {%- block styles %}
  File "/Users/alex/Developer/timetableSystem/app/templates/base.html", line 5, in block 'styles'
    <link rel="stylesheet" href="{{ url_for('static/css', filename='main.css') }}">
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static/css' with values ['filename']. Did you mean 'static' instead?
2021-12-11 21:56:59,197 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:14:11,346 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:14:32,503 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:15:22,794 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:17:04,261 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:18:44,019 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:20:01,563 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:22:47,706 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:24:29,620 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:28:34,477 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:29:58,985 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:30:29,389 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:30:56,821 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:34:35,683 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:34:52,142 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:37:12,697 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:37:36,210 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:38:47,938 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:39:42,397 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:40:45,908 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:41:06,555 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:43:50,357 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:45:04,217 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:53:50,321 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:54:04,048 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:54:43,502 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:57:28,044 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:57:45,972 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:58:02,666 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 22:58:12,837 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-12 09:04:54,316 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-12 09:07:16,026 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-12 09:13:53,159 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-12 09:14:00,024 ERROR: Exception on /login [POST] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 32, in login
    return redirect(url_for('home_admin'))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'home_admin'. Did you mean 'home' instead?
2021-12-12 09:14:32,948 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
